before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
language: r
warnings_are_errors: true
sudo: required
env:
  global:
    - CRAN=http://cran.rstudio.com
    - NOT_CRAN=true
    - _R_CHECK_CRAN_INCOMING_=false
    